name: telegram-info-bot
services:
  - name: telegram-bot
    type: web
    build:
      type: buildpack
      buildpack: heroku/nodejs
    instance_type: nano
    env:
      - name: NODE_ENV
        value: production
      - name: TELEGRAM_BOT_TOKEN
        secret: TELEGRAM_BOT_TOKEN
      - name: KOYEB_URL
        value: ${KOYEB_PUBLIC_DOMAIN}
    ports:
      - port: 8000
        protocol: http
    health_checks:
      - path: /
        port: 8000
        protocol: http
    scaling:
      min: 1
      max: 1
    regions:
      - fra
